apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: default
spec:
  ports:
    - name: api-gateway-port
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30007
  selector:
    app: api-gateway
  sessionAffinity: None
  type: NodePort

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: api-gateway-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: hub.dreams.com/dreams-spring-cloud/api-gateway:latest
        ports:
        - containerPort: 8080
