apiVersion: v1
kind: Service
metadata:
  labels:
    app: config-service
  name: config-service
  namespace: default
spec:
  ports:
    - name: config-service-port
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: user-service
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Development
metadata:
  name: config-service-deployment
spec:
  replicas: 1
  template:
    metdata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: hub.dreams.com/dreams-spring-cloud/config:latest
          ports:
            - containerPort: 8080
