apiVersion: v1
kind: Service
metadata:
  labels:
    app: config
  name: config
  namespace: default
spec:
  ports:
    - name: config-port
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30003
  selector:
    app: config
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Development
metadata:
  name: config-deployment
spec:
  replicas: 1
  template:
    metdata:
      labels:
        app: config
    spec:
      containers:
        - name: config
          image: hub.dreams.com/dreams-spring-cloud/config:latest
          ports:
            - containerPort: 8080
