apiVersion: v1
kind: Service
metadata:
  labels:
    app: eureka-service
  name: eureka-service
  namespace: default
spec:
  ports:
    - name: eureka-1-port
      port: 8761
      protocol: TCP
      targetPort: 8761
    - name: eureka-2-port
      port: 8762
      protocol: TCP
      targetPort: 8762
  selector:
    app: eureka-service
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: eureka-service-deployment
spec:
  repliccas: 1
  template:
    metadata:
      labels:
        app: eureka-service
    spec:
      containers:
        - name: eureka-1
          image: hub.dreams.com/dreams-spring-cloud/eureka:latest
          command:
            - "-Dspring.profiles.active=eureka-1"
          ports:
            - containerPort: 8761
        - name: eureka-2
          image: hub.dreams.com/dreams-spring-cloud/eureka:latest
          command:
            - "-Dspring.profiles.active=eureka-2"
          ports:
            - containerPort: 8762
