apiVersion: v1
kind: Service
metadata:
  labels:
    app: order
  name: order
  namespace: default
spec:
  ports:
    - name: order-port
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30005
  selector:
    app: order
  sessionAffinity: None
  type: NodePort

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: hub.dreams.com/dreams-spring-cloud/order:latest
        ports:
        - containerPort: 8080
