apiVersion: v1
kind: Service
metadata:
  labels:
    app: product
  name: product
  namespace: default
spec:
  ports:
    - name: product-port
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30004
  selector:
    app: product
  sessionAffinity: None
  type: NodePort

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: hub.dreams.com/dreams-spring-cloud/product:latest
        ports:
        - containerPort: 8080
