apiVersion: v1
kind: Service
metadata:
  labels:
    app: user
  name: user
  namespace: default
spec:
  ports:
    - name: user-port
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30006
  selector:
    app: user
  sessionAffinity: None
  type: NodePort

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: hub.dreams.com/dreams-spring-cloud/user:latest
        ports:
        - containerPort: 8080
