apiVersion: v1
kind: Service
metadata:
  labels:
    app: eureka-1
  name: eureka-1
  namespace: default
spec:
  ports:
    - name: eureka-1-port
      port: 8761
      protocol: TCP
      targetPort: 8761
      nodePort: 30001
  selector:
    app: eureka-1
  type: NodePort

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: eureka-deployment-1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-1
    spec:
      containers:
        - name: eureka-1
          image: hub.dreams.com/dreams-spring-cloud/eureka:latest
          args: ["--spring.profiles.active=eureka-1"]
          ports:
            - containerPort: 8761

