# Eureka高可用配置，
# 1. 两台，互相注册，
# 2. 三台，1向2，3注册，...
# 3. 多台，类似，...
eureka:
  client:
    service-url:
      defaultZone: http://eureka-2:8762/eureka/
  instance:
    prefer-ip-address: true
    #是否注册到 eureka, 高可用配置时默认为true
#    register-with-eureka: false
    #此为Eureka Server的自我保护,如果频繁的重启Client，Eureka会有红色错误提示，但仍然会显示Client存在此选项默认为true, 只可在开发模式下设为false, 生产环境下要恢复默认
#  server:
#    enable-self-preservation: false
spring:
  application:
    name: eureka-1
server:
  port: 8761